# Generated by Django 2.2.4 on 2020-01-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200110_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shortlisted',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default='1999-08-03'),
            preserve_default=False,
        ),
    ]
