# Generated by Django 2.2.4 on 2020-01-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20200109_1513'),
        ('users', '0011_auto_20200110_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shortlisted',
            field=models.ManyToManyField(to='event.Event'),
        ),
    ]
