# Generated by Django 2.2.4 on 2019-10-28 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 28, 15, 29, 0, 693172, tzinfo=utc)),
        ),
    ]
