# Generated by Django 2.2.4 on 2019-10-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20191029_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='verify',
            field=models.FileField(default='Django/proof/', upload_to='proof/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='model_pic',
            field=models.ImageField(default='Django/images/', upload_to='images/'),
        ),
    ]
