# Generated by Django 2.2.4 on 2019-10-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20191030_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='model_pic',
            field=models.ImageField(blank='True', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='verify',
            field=models.FileField(blank=True, upload_to='proof/'),
        ),
    ]
