# Generated by Django 2.2.4 on 2019-10-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20191030_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
