# Generated by Django 2.2.4 on 2019-10-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='verified',
        ),
    ]
