# Generated by Django 2.2.4 on 2019-10-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_event_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='model_pic',
            field=models.ImageField(default='images/', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='verify',
            field=models.FileField(default='proof/trek.png', upload_to='proof/'),
        ),
    ]
