# Generated by Django 2.2.4 on 2020-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20200109_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=25.6464341, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=75.4864, max_digits=15),
            preserve_default=False,
        ),
    ]
